// src/components/layout/header.jsx
import { Link } from "react-router-dom";
import Logo from "../../assets/logo-transparent.png";

function Menubar() {
  return (
    <header>
      <div className="container">
        <div className="flex justify-between align-middle items-center">
          <div className="flex items-center text-center">
            <img src={Logo} className="size-12 rounded-full mr-1" />
            <h1 className="font-audiowide font-bold text-2xl inline select-none">
              SUDO
            </h1>
          </div>
          <nav className="flex items-center">
            <ul className="grid grid-flow-col gap-x-6 text-foreground font-semibold">
              <Link
                to="/"
                className="py-2 pr-2 hover:text-primary transition-colors duration-200"
              >
                Home
              </Link>
              <Link
                to="/projects"
                className="py-2 px-3 hover:text-primary transition-colors duration-200 "
              >
                Projects
              </Link>
              <Link
                to="/our-team"
                className="py-2 px-3 hover:text-primary transition-colors duration-200"
              >
                Our Team
              </Link>
            </ul>
          </nav>
        </div>
        {/** rounded-md bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 p-1 */}
      </div>
    </header>
  );
}

export default Menubar;

// src/lib/components/Header.svelte
<header>
	<div class=" w-full h-full bg-slate-900">
		<div
			class="w-full rounded-md bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 p-1 bg-slate-900"
		>
			<div class="h-full w-full bg-gray-800">
				<nav class=" dark:bg-gray-800 border-solid border-transparent">
					<div class=" w-full md:block rounded-l-lg">
						<ul class=" flex w-full">
							<li>
								<a href="/" class=" block py-2 px-3 hover:text-red-600">Home</a>
							</li>
							<li>
								<a href="/" class=" block py-2 px-3 hover:text-red-600">Projects</a>
							</li>
							<li>
								<a href="/" class=" block py-2 px-3 hover:text-red-600">Our Team</a>
							</li>
							<li>
								<a href="/" class=" block py-2 px-3 hover:text-red-600">Contact</a>
							</li>
						</ul>
					</div>
				</nav>
			</div>
		</div>
	</div>
</header>
